pagopa/idpay-portal-merchants-operator-frontend

.devops/deploy-pipelines.yml

A deploy-pipelines.yml file has been added for the idpay-portal-merchants-operator-frontend repository

chore: EBE-7 add pipeline for deploy

---

.devops/deploy-pipelines.yml

This PR it's needed after the rename of dev branch from `release-dev` to `develop`

chore: Update deploy-pipelines.yml

---

.devops/deploy-pipelines.yml

fix: Add "VITE_" prefix to keycloak env

---

.devops/deploy-pipelines.yml
.env.development
package.json
src/App.tsx
src/components/ProtectedRoute.tsx
src/config/keycloak.ts
src/contexts/AuthContext.tsx
src/main.tsx
tsconfig.app.json
tsconfig.json
tsconfig.node.json
yarn.lock

Added keycloak configuration with keycloak-js library

[FEAT]: Added configuration with keycloak-js library

---

package-lock.json
src/components/Layout/Layout.tsx

fix: [EBE-40] fix for presentation

---

vite.config.ts

chore: exclude folders from coverage report

---

tsconfig.app.json
tsconfig.node.json
vite.config.ts

fixed configurations in vite config file and tsconfig file beacuse the build was failing

FIX: [EBE-55-FIX] fixed configurations in vite config and tsconfig

---

.devops/deploy-pipelines.yml

fix: Azure Front Door purge endpoint

---

src/pages/AcceptDiscount/AcceptDiscount.tsx

Fixed autocomplete, product list is created only when user type in the input field

FIX: [EBE-fix-autocomplete]: fixed autocomplete

---

src/pages/refundManagement/RefundManagement.tsx

fix: changed label name GTIN

---

src/pages/refundManagement/RefundManagement.test.tsx

fix class test label
fix class test label

fix: update class test label

---

.env.development
src/pages/products/Products.tsx

Fixed label and updated initiativeId

[FIX-DEV]: Updated initiativeId and fixed label

---

.env.development
src/components/FiltersForm/FiltersForm.test.tsx
src/components/FiltersForm/FiltersForm.tsx
src/pages/products/Products.tsx
src/pages/purchaseManagement/PurchaseManagement.tsx
src/pages/refundManagement/RefundManagement.tsx

fixed products page filters and added eprel link

FIX: [FIX-DEV] Fixed products page 

---

src/components/SideMenu/SideMenu.tsx
src/pages/profile/Profile.tsx

Added zip code, city and province on address field
Changed Profile button position on Sidebar
Missing values on address field and wrong Profile button position

fix: [EBE-203] added zip code, city and province to address field and change Profile button position on Sidebar

---

src/components/SideMenu/SideMenu.tsx

Added divider on SideMenu component
Added divider on SideMenu component
Missing divider on SideMenu component

feat: [EBE-219] added divider on SideMenu

---

src/components/SideMenu/SideMenu.tsx

feat: promote to UAT

---

.env.development
.env.uat
index.html
openApi/generated/merchants-swagger20.json
openApi/openapi.merchants.op.portal.yml
src/api/generated/merchants/PreviewPaymentDTO.ts
src/api/generated/merchants/ProductDTO.ts
src/components/Autocomplete/AutocompleteComponent.tsx
src/components/FiltersForm/FiltersForm.tsx
src/components/Header/Header.test.tsx
src/components/Header/Header.tsx
src/locale/it.json
src/pages/acceptDiscount/AcceptDiscount.tsx
src/pages/products/Products.tsx
src/pages/purchaseManagement/PurchaseManagement.tsx
src/pages/refundManagement/RefundManagement.tsx
src/pages/summaryAcceptDiscount/SummaryAcceptDiscount.tsx
src/utils/helpers.tsx

Added identity verification check in accept discount page

FEAT: [DEVELOP] Added identity verification 

---

src/App.tsx
src/components/BreadcrumbsBox/BreadcrumbsBox.tsx
src/components/BreadcrumbsBox/breadcrumsBox.module.css
src/locale/it.json
src/pages/purchaseManagement/PurchaseManagement.tsx
src/pages/refundManagement/RefundManagement.tsx
src/pages/reverse/Reverse.tsx
src/pages/reverse/reverse.module.css
src/pages/summaryAcceptDiscount/SummaryAcceptDiscount.tsx
src/routes.ts

FEAT: [DEVELOP] Promote to UAT

---

src/pages/profile/Profile.tsx

Fixed address empty field in Profile page
Fixed address empty field in Profile page

fix: [EBE-275] fixed Profile page address empty field

---

src/pages/refundManagement/RefundManagement.tsx

Added time in date and time filed in transaction details component
Added time in date and time filed in transaction details component
Missing time in date and time filed in transaction details component

fix: [EBE-276] added time in date and time field
